### ISSUE TITLE
Support screenshot comparisons in browser checks

### ISSUE THREAD

**Issue by jonoc330** [checkly/public-roadmap#272]
**Is your feature request related to a problem? Please describe.**
I'm trying to compare two screenshots in my Checkly playwright check.. I.e, take a screenshot of a particular element, load up a different page, and compare an element on that page with the screenshot.

I can't use Playwright's native functionality in Checkly: https://playwright.dev/docs/test-assertions#screenshot-assertions-to-match-snapshot-1

**Describe the solution you'd like**
There are [several pixel diff npm packages out there](https://www.npmjs.com/package/pixel-buffer-diff), although I'd prefer to use the native functionality from Playwright if possible. 

**Describe alternatives you've considered**
Did attempt using `expect` from Playright as well as the raw `expect` package in runtimes but that doesn't show up anything useful.

**Comment by darkostanimirovic** [comment]
Hi @jonoc330, thanks for reaching out.

We don't support Playwright's visual comparisons yet, but there's a feature request already. Can you upvote and comment on that one? https://github.com/checkly/public-roadmap/issues/179 I will close this as a duplicate since it relies on the same API, and to direct people to one place for the feature request. Feel free to comment/clarify here if needed.
