### ISSUE TITLE
JSON check for multiple values

### ISSUE THREAD

**Issue by pampy** [checkly/public-roadmap#44]
**Is your feature request related to a problem? Please describe.**
We have multiple APIs which return an array of objects, for example a list of videos.
Every video has certain fields like a video URL.
I can query the videos with a selector like $.videos..url

According to the checkly documentation (https://checklyhq.com/docs/api-checks/assertions/#json-responses-with-json-path)
"Your JSON path expression should return exactly one value. JSON path has the option to returns arrays of value, but Checkly cannot assert them."

**Describe the solution you'd like**
It would be great if we could evaluate all values against the same check, for example
$.videos..url CONTAINS "https:/...".

**Describe alternatives you've considered**
Currently we're checking for the latest videos only, meaning I check for something like
$.videos[-1:].url
$.videos[-2:].url
etc.
This means we need to add multiple checks but still cannot test all URLs without knowing how many elements we actually have (which is tricky in dynamic lists).

**Comment by tnolet** [comment]
@pampy thanks for reporting

**Comment by tnolet** [comment]
@pampy We are going to look into this soon. I did a short analysis and the scope & implementation path are clearer to us. I'm also looping in @batuhan for awareness

**Comment by tnolet** [comment]
@pampy we have this working quite well, but there are some small corner cases where it will break current behaviour for customers currently assertion JSON arrays as strings. For example, on of our own checks on our staging broke because we were asserting the following:


1. `$.tags` parses out an array from a JSON body
2. The array is for instance: '["sometag", "and_another"]' 
3. We check if the string CONTAINS "tag"

This works fine now because the whole string does contain the substring "tag". The array is not treated as an array.

In the new situation, we would validate each string in the array and check if it contains the substring "tag". This fails because the second item "and_another" does not contain that substring.

We will have a think over here at the HQ to see how we want to deal with this and propose either a migration, alternative or inform customers beforehand of the change.

**Comment by pampy** [comment]
Hi @tnolet!
Thanks for taking a look at it.
I didn't assume that you would use that for querying over the result array, that certainly makes things complicated now.
I'll also think about it, if I got a good idea how to solve it.
Maybe you find a nice solution for it, I don't have a good idea spontaneously unfortunately 😅

**Comment by pampy** [comment]
Wow @tnolet that's great news!
So you went the road of breaking legacy usage and implement the check for every element like we proposed it?

**Comment by tnolet** [comment]
@pampy In short yes. 

It makes the most sense to do what the JSON path queries suggest you can do and we did not do this. 

Longer story: We made the change and made sure we have all tests green. Still we found a corner case in our staging environment so there might be some other corner case. Also, the most used JSON path queries that involve arrays are all 100% "backwards compatible", i.e. `$[0]` $[-1:] etc.

However, the only real breaking change will happen if folks right now run specific textual or numerical comparison assertions on a full array. Our calculated guess is those cases are minimal. We had one of those in our staging. That assertion actually made no real sense. So this is better for everyone. Better do it now than in a year!

**Comment by pampy** [comment]
Very glad to hear this! Hope everything's going well, also for other customers :-)

**Comment by tnolet** [comment]
This has been rolled out and is live right now.
